### ISSUE TITLE
Is thread implementation necessary?

### ISSUE THREAD

**Issue by EnJiang** [moonbings/connect6_rl#2]
Hi, moonbings!
Your codes are elegant and easy to understand.
I am a little bit confused about your multi-thread implementation [here](https://github.com/moonbings/connect6_rl/blob/18d7bf1779183f847607b6038849b8a0cc33de8f/core/agent.py#L169) in agent.py though.
To my understanding, you want to accelerate the VCDT search. However, Python has 
GIL and since we have computationally intensive tasks here, I think multi-thread, as opposed to multi-process implementation, would actually slow your program down.
Any thoughts?
Also, I wonder would it be ok for me to PR a multi-process version.

**Comment by moonbings** [comment]
Hi EnJiang!
Thank you for your interest in this project.
I tried to find the way to implement this code using multiprocessing, but I didn't find a good way to do it.
Of course! You're very welcome to PR your multi-process version! I hope the performance of the VCDT search will be improved by your contribution.

**Comment by EnJiang** [comment]
After trying several methods I did not get it working too. Closing.
